version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: Asia/Calcutta
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack-cli
    versions:
    - ">= 0"
  - dependency-name: postcss
    versions:
    - 8.2.10
    - 8.2.11
    - 8.2.12
    - 8.2.5
    - 8.2.6
    - 8.2.7
    - 8.2.8
    - 8.2.9
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.10
    - 24.1.5
    - 24.1.6
    - 24.1.7
    - 24.1.8
    - 24.1.9
    - 24.2.0
    - 24.2.1
    - 24.3.0
    - 24.3.1
    - 24.3.2
    - 24.3.3
    - 24.3.4
    - 24.3.5
  - dependency-name: eslint
    versions:
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@quintype/build"
    versions:
    - 3.10.3
    - 3.11.0
    - 3.12.0
  - dependency-name: eslint-plugin-react
    versions:
    - 7.23.0
    - 7.23.1
  - dependency-name: "@quintype/framework"
    versions:
    - 4.10.2
    - 4.10.3
    - 4.10.4
    - 4.12.1
    - 4.12.2
    - 4.12.3
    - 4.12.5
    - 4.12.6
    - 4.13.0
    - 4.13.1
    - 4.7.6
    - 4.8.0
    - 4.8.2
    - 4.8.3
    - 4.8.4
  - dependency-name: react-redux
    versions:
    - 7.2.3
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: "@quintype/components"
    versions:
    - 2.25.4
    - 2.26.1
    - 2.26.2
    - 2.27.1
  - dependency-name: "@quintype/bridgekeeper-js"
    versions:
    - 2.2.1
    - 2.2.2
    - 2.3.0
  - dependency-name: mocha
    versions:
    - 8.3.1
    - 8.3.2
  - dependency-name: stylelint
    versions:
    - 13.10.0
    - 13.11.0
    - 13.12.0
    - 13.9.0
  - dependency-name: "@quintype/seo"
    versions:
    - 1.38.28
  - dependency-name: lodash
    versions:
    - 4.17.21
  - dependency-name: ini
    versions:
    - 1.3.7
    - 1.3.8
  - dependency-name: superagent
    versions:
    - 6.1.0
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.1
  - dependency-name: stylelint-scss
    versions:
    - 3.19.0
  - dependency-name: formiojs
    versions:
    - 4.12.6
    - 4.12.7
  - dependency-name: node-notifier
    versions:
    - 8.0.1
  - dependency-name: "@quintype/backend"
    versions:
    - 1.23.14
  - dependency-name: webpack-bundle-analyzer
    versions:
    - 4.4.0
