#!/bin/bash -e

# npm install
npm run copy-arrow

# Do not overwrite the import in line 1 in fullscreenimages.scss

npm run compile
supervisord -n -c <(cat <<EOF
[supervisord]

[program:app-server]
command=npm run dev-server
stdout_events_enabled=true
stderr_events_enabled=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stopasgroup=true

[program:asset-server]
command=npm run asset-server
stdout_events_enabled=true
stderr_events_enabled=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stopasgroup=true
EOF
)
