#!/bin/bash -e

npm install
npm run copy-arrow

# Do not overwrite these two files - line 1 in fullscreenimages.scss, line 23 to 26 in author-image.css and line 1 in author.m.css

npm run compile
supervisord -n -c <(cat <<EOF
[supervisord]

[program:app-server]
command=npm run dev-server
stdout_events_enabled=true
stderr_events_enabled=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stopasgroup=true

[program:asset-server]
command=npm run asset-server
stdout_events_enabled=true
stderr_events_enabled=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stopasgroup=true
EOF
)
