import React, { useState } from 'react';
import './VitalsReport.css';

/**
 * Reusable Core Web Vitals Diagnostic Report Component.
 * 
 * @param {object} props
 * @param {object} props.reportData The parsed JSON report data generated by cwv-inspector.
 */
export default function VitalsReport({ reportData }) {
  if (!reportData) {
    return <div className="vitals-report-empty">No report data provided. Please load a valid cwv-inspector JSON report.</div>;
  }

  const {
    projectName,
    clientName,
    gitBranch,
    auditDate,
    auditUrl,
    healthScore,
    lighthouseData,
    summary,
    issues = []
  } = reportData;

  const [activeTab, setActiveTab] = useState('mobile');
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedSeverity, setSelectedSeverity] = useState('all');
  const [selectedCategory, setSelectedCategory] = useState('all');
  const [expandedIndex, setExpandedIndex] = useState(null);

  const hasLighthouse = lighthouseData && lighthouseData.mobile;
  const activeLhData = hasLighthouse ? (activeTab === 'mobile' ? lighthouseData.mobile : lighthouseData.desktop) : null;
  const activeScore = hasLighthouse ? (activeTab === 'mobile' ? healthScore.mobile : healthScore.desktop) : reportData.healthScore;

  // Compute status styles
  let scoreClass = 'good';
  let scoreTextClass = 'good-text';
  let scoreStatus = 'Excellent';

  if (activeScore < 50) {
    scoreClass = 'poor';
    scoreTextClass = 'danger-text';
    scoreStatus = 'Poor';
  } else if (activeScore < 90) {
    scoreClass = 'needs-improvement';
    scoreTextClass = 'warning-text';
    scoreStatus = 'Needs Improvement';
  }

  // Helper to compute range bar position and segment styles
  const getMetricDetails = (type) => {
    let statusClass = 'warning', statusLabel = 'Static Only', valueDisplay = 'N/A', textClass = 'warning-text', subdesc = 'No runtime measured.', percent = 0;

    if (activeLhData) {
      if (type === 'lcp') {
        const lcpSec = activeLhData.lcp.value / 1000;
        valueDisplay = `${lcpSec.toFixed(2)}s`;
        if (lcpSec <= 2.5) {
          statusClass = 'good'; statusLabel = 'Good'; textClass = 'good-text'; subdesc = 'Excellent rendering speed.';
          percent = (lcpSec / 2.5) * 33;
        } else if (lcpSec <= 4.0) {
          statusClass = 'warning'; statusLabel = 'Needs Work'; textClass = 'warning-text'; subdesc = 'Needs work (over 2.5s).';
          percent = 33 + ((lcpSec - 2.5) / 1.5) * 33;
        } else {
          statusClass = 'poor'; statusLabel = 'Poor'; textClass = 'danger-text'; subdesc = `${(lcpSec - 2.5).toFixed(1)}s over the limit.`;
          percent = Math.min(100, 66 + ((lcpSec - 4.0) / 4.0) * 34);
        }
      } else if (type === 'cls') {
        const clsVal = activeLhData.cls.value;
        valueDisplay = clsVal.toFixed(3);
        if (clsVal <= 0.1) {
          statusClass = 'good'; statusLabel = 'Good'; textClass = 'good-text'; subdesc = 'No layout shift detected.';
          percent = (clsVal / 0.1) * 33;
        } else if (clsVal <= 0.25) {
          statusClass = 'warning'; statusLabel = 'Needs Work'; textClass = 'warning-text'; subdesc = 'Some layout shifts present.';
          percent = 33 + ((clsVal - 0.1) / 0.15) * 33;
        } else {
          statusClass = 'poor'; statusLabel = 'Poor'; textClass = 'danger-text'; subdesc = 'Poor layout stability.';
          percent = Math.min(100, 66 + ((clsVal - 0.25) / 0.5) * 34);
        }
      } else if (type === 'tbt') {
        const tbtVal = Math.round(activeLhData.tbt.value);
        valueDisplay = `${tbtVal}ms`;
        if (tbtVal <= 200) {
          statusClass = 'good'; statusLabel = 'Good'; textClass = 'good-text'; subdesc = 'Main thread is responsive.';
          percent = (tbtVal / 200) * 33;
        } else if (tbtVal <= 600) {
          statusClass = 'warning'; statusLabel = 'Needs Work'; textClass = 'warning-text'; subdesc = 'Some input blocking present.';
          percent = 33 + ((tbtVal - 200) / 400) * 33;
        } else {
          statusClass = 'poor'; statusLabel = 'Poor'; textClass = 'danger-text'; subdesc = `${tbtVal - 200}ms over the limit.`;
          percent = Math.min(100, 66 + ((tbtVal - 600) / 1000) * 34);
        }
      }
    }

    return { statusClass, statusLabel, valueDisplay, textClass, subdesc, percent };
  };

  const lcp = getMetricDetails('lcp');
  const cls = getMetricDetails('cls');
  const tbt = getMetricDetails('tbt');

  // Filter Issues
  const filteredIssues = issues.filter(issue => {
    const matchesSearch = searchQuery === '' || 
      issue.message.toLowerCase().includes(searchQuery) ||
      issue.impact.toLowerCase().includes(searchQuery) ||
      issue.suggestion.toLowerCase().includes(searchQuery);
    
    const matchesSeverity = selectedSeverity === 'all' || issue.severity.toLowerCase() === selectedSeverity;
    const matchesCategory = selectedCategory === 'all' || issue.cwv.toLowerCase() === selectedCategory;

    return matchesSearch && matchesSeverity && matchesCategory;
  });

  // Calculate counts for filters
  const getCounts = (sev) => issues.filter(i => i.severity.toLowerCase() === sev).length;

  return (
    <div className="vitals-report-container">
      {/* Brand Header */}
      <header className="vitals-header">
        <div className="vitals-brand">
          <div className="vitals-brand-top">
            <img className="vitals-logo-img" src="https://cdn.prod.website-files.com/64819da6f9ae7ae6e232658c/66ed2342896c97c223a0a15c_256x256%20Quintype%20Logo.png" alt="Quintype Logo" />
            <span className="vitals-logo">ACE</span>
            <span className="vitals-title">Team Web Vitals Lab</span>
          </div>
          <div className="vitals-meta">
            <span>Prepared for: {clientName}</span>
            <span>&bull; Author: Siripireddy Giri</span>
            <span>&bull; {auditDate}</span>
          </div>
        </div>
        <div className="vitals-header-main">
          <div className="vitals-diagnostic-tag">CORE WEB VITALS &mdash; DIAGNOSTIC READOUT</div>
          <h1 className="vitals-project-title">
            {projectName} &bull; <span className="vitals-url-sub">{auditUrl}</span>
          </h1>
        </div>
      </header>

      {/* Tabs Switcher */}
      {hasLighthouse && (
        <div className="vitals-tabs-container">
          <div className="vitals-tabs">
            <button 
              className={`vitals-tab-btn ${activeTab === 'mobile' ? 'active' : ''}`}
              onClick={() => setActiveTab('mobile')}
            >
              Mobile
            </button>
            <button 
              className={`vitals-tab-btn ${activeTab === 'desktop' ? 'active' : ''}`}
              onClick={() => setActiveTab('desktop')}
            >
              Desktop
            </button>
          </div>
        </div>
      )}

      {/* Dashboard Grid */}
      <div className="vitals-grid">
        {/* Health Score circular card */}
        <div className="vitals-card health-score-card">
          <div className="vitals-gauge-container">
            <div className={`vitals-gauge-value ${scoreClass}`}>{activeScore}</div>
            <div className="vitals-gauge-label">Health Score</div>
          </div>
          <div className="vitals-health-meta">
            <div className={`vitals-health-status ${scoreTextClass}`}>{scoreStatus}</div>
            <div className="vitals-health-desc">{summary.high} high-impact issues identified in codebase.</div>
          </div>
        </div>

        {/* LCP Card */}
        <div className="vitals-card">
          <div className="vitals-card-header-top">
            <div className="vitals-card-title-group">
              <span className="vitals-card-abbr">LCP</span>
              <span className="vitals-card-fullname">Largest Contentful Paint</span>
            </div>
            <span className={`vitals-status-badge ${lcp.statusClass}`}>{lcp.statusLabel}</span>
          </div>
          <div className={`vitals-card-value ${lcp.textClass}`}>{lcp.valueDisplay}</div>
          <div className="vitals-card-subdesc">{lcp.subdesc}</div>
          <div className="vitals-range-bar">
            <div className="vitals-range-indicator" style={{ left: `${lcp.percent}%` }}></div>
            <div className="vitals-range-segments">
              <span className="vitals-seg good"></span>
              <span className="vitals-seg warning"></span>
              <span className="vitals-seg poor"></span>
            </div>
          </div>
          <div className="vitals-range-labels">
            <span>Good &le;2.5s</span>
            <span>Needs Work &le;4s</span>
            <span>Poor &gt;4s</span>
          </div>
        </div>

        {/* CLS Card */}
        <div className="vitals-card">
          <div className="vitals-card-header-top">
            <div className="vitals-card-title-group">
              <span className="vitals-card-abbr">CLS</span>
              <span className="vitals-card-fullname">Cumulative Layout Shift</span>
            </div>
            <span className={`vitals-status-badge ${cls.statusClass}`}>{cls.statusLabel}</span>
          </div>
          <div className={`vitals-card-value ${cls.textClass}`}>{cls.valueDisplay}</div>
          <div className="vitals-card-subdesc">{cls.subdesc}</div>
          <div className="vitals-range-bar">
            <div className="vitals-range-indicator" style={{ left: `${cls.percent}%` }}></div>
            <div className="vitals-range-segments">
              <span className="vitals-seg good"></span>
              <span className="vitals-seg warning"></span>
              <span className="vitals-seg poor"></span>
            </div>
          </div>
          <div className="vitals-range-labels">
            <span>Good &le;0.1</span>
            <span>Needs Work &le;0.25</span>
            <span>Poor &gt;0.25</span>
          </div>
        </div>

        {/* TBT Card */}
        <div className="vitals-card">
          <div className="vitals-card-header-top">
            <div className="vitals-card-title-group">
              <span className="vitals-card-abbr">TBT</span>
              <span className="vitals-card-fullname">Total Blocking Time</span>
            </div>
            <span className={`vitals-status-badge ${tbt.statusClass}`}>{tbt.statusLabel}</span>
          </div>
          <div className={`vitals-card-value ${tbt.textClass}`}>{tbt.valueDisplay}</div>
          <div className="vitals-card-subdesc">{tbt.subdesc}</div>
          <div className="vitals-range-bar">
            <div className="vitals-range-indicator" style={{ left: `${tbt.percent}%` }}></div>
            <div className="vitals-range-segments">
              <span className="vitals-seg good"></span>
              <span className="vitals-seg warning"></span>
              <span className="vitals-seg poor"></span>
            </div>
          </div>
          <div className="vitals-range-labels">
            <span>Good &le;200ms</span>
            <span>Needs Work &le;600ms</span>
            <span>Poor &gt;600ms</span>
          </div>
        </div>
      </div>

      {/* Performance Score Track */}
      {activeLhData && (
        <div className="vitals-slider-section">
          <div className="vitals-slider-header">
            <div className="vitals-slider-title-group">
              <h4>Performance Score</h4>
              <div className="vitals-slider-val">{Math.round(activeLhData.performanceScore)}</div>
            </div>
            <div className="vitals-slider-target">
              {90 - Math.round(activeLhData.performanceScore) > 0 
                ? `${90 - Math.round(activeLhData.performanceScore)} points below the 90 target`
                : 'Meets the 90 target!'}
            </div>
          </div>
          <div className="vitals-slider-track-container">
            <div className="vitals-slider-track">
              <div 
                className="vitals-slider-track-fill" 
                style={{ width: `${Math.round(activeLhData.performanceScore)}%` }}
              ></div>
              <div 
                className="vitals-slider-handle" 
                style={{ left: `${Math.round(activeLhData.performanceScore)}%` }}
              ></div>
            </div>
          </div>
        </div>
      )}

      {/* Fix These First */}
      <div className="vitals-fix-section">
        <h3 className="vitals-section-title-tag">Fix these first</h3>
        <div className="vitals-fix-grid">
          {issues.slice(0, 3).map((issue, idx) => (
            <div className="vitals-fix-card" key={idx}>
              <div>
                <div className="vitals-fix-card-num">0{idx + 1}</div>
                <div className="vitals-fix-card-title">{issue.message}</div>
              </div>
              <div className="vitals-fix-card-savings">
                {issue.occurrences && issue.occurrences.length > 1
                  ? `${issue.occurrences.length} files affected`
                  : (issue.file.includes('Runtime Audit') ? 'Lighthouse' : issue.file.split('/').pop())}
              </div>
            </div>
          ))}
          {issues.length === 0 && (
            <div className="vitals-fix-card-empty">No issues found!</div>
          )}
        </div>
      </div>

      {/* Controls / Filter Row */}
      <div className="vitals-controls-row">
        <div className="vitals-search-box">
          <span className="vitals-search-icon">🔍</span>
          <input 
            type="text" 
            placeholder="Search issues, files, or fixes..." 
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value.toLowerCase())}
          />
        </div>
        <div className="vitals-filter-group">
          <button 
            className={`vitals-filter-pill ${selectedSeverity === 'all' ? 'active' : ''}`}
            onClick={() => setSelectedSeverity('all')}
          >
            All severities
          </button>
          <button 
            className={`vitals-filter-pill ${selectedSeverity === 'high' ? 'active' : ''}`}
            onClick={() => setSelectedSeverity('high')}
          >
            High - {getCounts('high')}
          </button>
          <button 
            className={`vitals-filter-pill ${selectedSeverity === 'medium' ? 'active' : ''}`}
            onClick={() => setSelectedSeverity('medium')}
          >
            Medium - {getCounts('medium')}
          </button>
          <button 
            className={`vitals-filter-pill ${selectedSeverity === 'low' ? 'active' : ''}`}
            onClick={() => setSelectedSeverity('low')}
          >
            Low - {getCounts('low')}
          </button>
        </div>
        <div className="vitals-filter-group">
          <button 
            className={`vitals-filter-pill ${selectedCategory === 'all' ? 'active' : ''}`}
            onClick={() => setSelectedCategory('all')}
          >
            All categories
          </button>
          {['lcp', 'cls', 'inp', 'a11y'].map(cat => (
            <button 
              key={cat}
              className={`vitals-filter-pill ${selectedCategory === cat ? 'active' : ''}`}
              onClick={() => setSelectedCategory(cat)}
            >
              {cat.toUpperCase()}
            </button>
          ))}
        </div>
      </div>

      {/* Issues Accordions List */}
      <div className="vitals-issues-list">
        {filteredIssues.map((issue, index) => {
          const isExpanded = expandedIndex === index;
          return (
            <div className={`vitals-issue-card ${isExpanded ? 'expanded' : ''}`} key={index}>
              <div 
                className="vitals-issue-header" 
                onClick={() => setExpandedIndex(isExpanded ? null : index)}
              >
                <div className="vitals-issue-left">
                  <span className="vitals-issue-idx">#{String(index + 1).padStart(2, '0')}</span>
                  <div className="vitals-issue-badges">
                    <span className={`vitals-badge ${issue.severity.toLowerCase()}`}>{issue.severity}</span>
                    <span className="vitals-badge cat">{issue.cwv}</span>
                  </div>
                  <span className="vitals-issue-title-text">{issue.message}</span>
                </div>
                <div className="vitals-issue-right">
                  <span className="vitals-affected-summary">
                    {issue.occurrences && issue.occurrences.length > 1
                      ? `${issue.occurrences.length} files`
                      : (issue.file.includes('Runtime Audit') ? 'Lighthouse' : issue.file.split('/').pop())}
                  </span>
                  <span className="vitals-accordion-arrow">▼</span>
                </div>
              </div>
              
              {isExpanded && (
                <div className="vitals-issue-details">
                  <div className="vitals-details-desc">{issue.impact}</div>
                  <div className="vitals-details-fix">
                    <div className="vitals-details-fix-title">Recommendation</div>
                    <div className="vitals-details-fix-text">{issue.suggestion}</div>
                  </div>
                  {issue.occurrences && issue.occurrences.length > 0 && (
                    <div className="vitals-details-files">
                      <div className="vitals-details-files-title">Affected Files:</div>
                      <div className="vitals-files-list">
                        {issue.occurrences.map((o, fIdx) => (
                          <div className="vitals-file-row" key={fIdx}>
                            <span className="vitals-file-path">{o.file}</span>
                            <span className="vitals-file-line">{o.line && o.line !== '-' ? `:${o.line}` : ''}</span>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}
                </div>
              )}
            </div>
          );
        })}
        {filteredIssues.length === 0 && (
          <div className="vitals-issue-empty">No matching findings found.</div>
        )}
      </div>
    </div>
  );
}
